#Esto va en cada proyecto

FROM adoptopenjdk/openjdk11:alpine-jre
# Aquí ponemos la version del JDK de java que va a ejecutar nuestro proyecto

ARG JAR_FILE=spring-boot-web.jar
# indica en dónde de encuentra el archivo JAR de nuestro proyecto

COPY ${JAR_FILE} app.jar
# Copiamos ek archivo y lo renombramos a "app.jar"

ENTRYPOINT ["java","jar","app.jar"]
#ejecucíon del comando "java -jar app.jar"

EXPOSE 8080 
# podemos configurar a todos los proyectos al mismo puerto. 8888??