version: '3.3'
services:
  catalog-service:
    build: final-backend-victoria-suarez/catalog-service
    mem_limit: 512m
    ports:
      - "8080:8080"

  movie-service:
    build: final-backend-victoria-suarez/movie-service
    mem_limit: 512m
    ports:
      - "8080:8080"

  serie-service:
    build: final-backend-victoria-suarez/serie-service
    mem_limit: 512m
    ports:
      - "8080:8080"

  eureka-server:
    build: spring-cloud/eureka-server
    mem_limit: 512m
    ports:
      - "8761:8761"

  mysql: #Config. Base de datos
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'digitalhouse-dev'
      MYSQL_USER: 'usr-digitalhouse'
      MYSQL_PASSWORD: 'pwd-digitalhouse'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted

  mongodb:
      image: mongo
      restart: always
      mem_limit: 512m
      ports:
        - "27017:27017"
      command: mongod
      healthcheck:
        test: "mongo --eval 'db.stats().ok'"
        interval: 5s
        timeout: 2s
        retries: 60